### ISSUE TITLE
Release fails with Java 17

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/oss-quickstart#15]
See the execution of the release job, ran into this one: https://issues.sonatype.org/browse/OSSRH-66257.

@aalmiray, I believe we've had this before. Did we do that XStream dependency version override to prevent it?

**Comment by aalmiray** [comment]
Don't remember seeing this error before. Does the release must use Java 17? Downgrading to 11 may solve the issue. Specifying an explicit version for xstream in the plugin's dependencies as shown at https://github.community/t/github-actions-bot-email-address/17204/4 would also work.

**Comment by gunnarmorling** [comment]
yes, no problem with going to 11, apart from the shame of not using the latest and greatest of course :)

**Comment by gunnarmorling** [comment]
So the release went out, using 11, and the artifacts are there: https://repo1.maven.org/maven2/org/moditect/ossquickstart/oss-quickstart-simple-archetype/1.0.0.Alpha1/. It still isn't found though :/

```
mvn archetype:generate -B \
  -DarchetypeGroupId=org.moditect.ossquickstart \
  -DarchetypeArtifactId=oss-quickstart-simple-archetype \
  -DarchetypeVersion=1.0.0.Alpha1 \
  -DgroupId=com.example.demos \
  -DartifactId=fancy-project \
  -Dversion=1.0.0-SNAPSHOT \
  -DmoduleName=com.example.fancy
```

Wondering whether some special trickery is needed in terms of deploying an archetype with the right metadata to Maven Central 🤔 ?

**Comment by gunnarmorling** [comment]
Release is done with 11, artifacts can also be resolved now.
