### ISSUE TITLE
Update GitHub Actions steps to use @v3

### ISSUE THREAD

**Issue by tedyoung** [moditect/oss-quickstart#26]
Latest versions of `checkout` and `setup-java` are `@v3`. This also means `cache@v2` is no longer needed separately (it's included in setup-java).

I can submit a PR for this, if desired.

**Comment by gunnarmorling** [comment]
Hey @tedyoung, that sounds good. A PR would be welcomed. Could you please update the workflow definition in the archetype template (see README for details) as well as the workflow of this project itself? Thanks!

**Comment by gunnarmorling** [comment]
Hey there, still interested in sending a PR for this?

**Comment by gunnarmorling** [comment]
Upgraded to v4 just now.
