### ISSUE TITLE
Set up release and GH Actions

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/oss-quickstart#6]
* Release the archetype using JReleaser
* Build PRs and upon pushes to _main_

**Comment by gunnarmorling** [comment]
Could you perhaps help with this (in particular the JReleaser part), @aalmiray? Perhaps I should create the actual archetype first, though?

**Comment by aalmiray** [comment]
Yup, I think we need the archetype project first

**Comment by gunnarmorling** [comment]
Ok, I'm planning to work on this in the course of this week. Thanks!

>

**Comment by gunnarmorling** [comment]
I think the template project is in a good state already, wouldn't mind
taking this as the basis for a first version. Would love to hear about your
feedback on it too.

>

**Comment by gunnarmorling** [comment]
Hey @aalmiray, alrighty; so basic CI via GitHub Actions is already in place. And there's also first version of the single module archetype: https://github.com/moditect/oss-quickstart/tree/main/oss-quickstart-archetype-simple.

I.e. whenever you got the time, you could hook this up with the release machinery. Note this is already a multi-module project (although with a single module at this point), which inherits from the Maven org parent.

**Comment by gunnarmorling** [comment]
Done. Thx, @aalmiray!

**Comment by gunnarmorling** [comment]
Hey @aalmiray, one question actually: is any special config needed for deploying an archetype to Maven Central? Will it go into the archetype catalog automatically? Or does the user have to specify the exact archetype group id / artifact id in order to use it?

**Comment by aalmiray** [comment]
Hmm I don't think there is any special setup other than `<packaging>maven-archetype</packaging>`.

**Comment by gunnarmorling** [comment]
Ok, cool. So looks like I'll press the release button some time this week
then :)

>
